'''
You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

b[0] is equal to a[0];
b[1] is equal to the last element of a;
b[2] is equal to a[1];
b[3] is equal to the second-last element of a;
b[4] is equal to a[2];
b[5] is equal to the third-last element of a;
and so on.
Your task is to determine whether the new array b is sorted in strictly ascending order or not.

For a = [1, 3, 5, 6, 4, 2], the output should be solution(a) = true.

The new array b will look like [1, 2, 3, 4, 5, 6], which is in strictly ascending order, so the answer is true.
'''

def solution(a):
    b = []
    rev = -1
    for i in range(len(a)//2):
        b.append(a[i])
        b.append(a[rev])
        rev -= 1
    
    if len(a)%2 != 0:
        b.append(a[len(a)//2])
        
    b_set = set(b)
    if len(b)!=len(b_set):
        return False
        
    b_test = b[:]
    b_test.sort(reverse=False)
    
    
    return b == b_test